// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrwnnlldufajuojkcqmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyd25ubGxkdWZhanVvamtjcW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjkyMTIsImV4cCI6MjA3MTQ0NTIxMn0.LQfDeBb7vrLGb9-0RcNWtZHcOkPr3R23DVDvVFM8X7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});